'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class ProductosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ProductosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function ListadoProductos(fechaDesde As Nullable(Of Date), fechaHasta As Nullable(Of Date), tipoProducto As Nullable(Of Integer), stockMayorA As Nullable(Of Integer), stockMenorA As Nullable(Of Integer)) As ObjectResult(Of ListadoProductos_Result)
        Dim fechaDesdeParameter As ObjectParameter = If(fechaDesde.HasValue, New ObjectParameter("fechaDesde", fechaDesde), New ObjectParameter("fechaDesde", GetType(Date)))

        Dim fechaHastaParameter As ObjectParameter = If(fechaHasta.HasValue, New ObjectParameter("fechaHasta", fechaHasta), New ObjectParameter("fechaHasta", GetType(Date)))

        Dim tipoProductoParameter As ObjectParameter = If(tipoProducto.HasValue, New ObjectParameter("tipoProducto", tipoProducto), New ObjectParameter("tipoProducto", GetType(Integer)))

        Dim stockMayorAParameter As ObjectParameter = If(stockMayorA.HasValue, New ObjectParameter("stockMayorA", stockMayorA), New ObjectParameter("stockMayorA", GetType(Integer)))

        Dim stockMenorAParameter As ObjectParameter = If(stockMenorA.HasValue, New ObjectParameter("stockMenorA", stockMenorA), New ObjectParameter("stockMenorA", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ListadoProductos_Result)("ListadoProductos", fechaDesdeParameter, fechaHastaParameter, tipoProductoParameter, stockMayorAParameter, stockMenorAParameter)
    End Function

End Class
